[package]
name = "fft_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
num = "0.3.0"
num-complex = "0.3"

[dev-dependencies]
criterion = "0.3"
